-- ─── SUBMISSIONS & DEALS TABLES (synapsis schema) ──────────────────────────
-- Run this in your Supabase SQL Editor: https://uslmejdctlglropgqzmc.supabase.co/project/default/sql
-- This creates persistent tables to replace the ephemeral JSON file storage.

-- 1. Submissions table (replaces data/submissions.json)
CREATE TABLE IF NOT EXISTS synapsis.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    company TEXT DEFAULT '',
    need TEXT DEFAULT '',
    budget TEXT DEFAULT '',
    message TEXT DEFAULT '',
    date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Deals table (replaces data/deals.json)
CREATE TABLE IF NOT EXISTS synapsis.deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token TEXT UNIQUE NOT NULL,
    submission_id BIGINT REFERENCES synapsis.submissions(id),
    name TEXT NOT NULL,
    company TEXT DEFAULT '',
    need TEXT DEFAULT '',
    budget TEXT DEFAULT '',
    message TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT NOT NULL DEFAULT 'pending',
    phase INTEGER NOT NULL DEFAULT 0,
    elected_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    rejection_note TEXT,
    extended_until TIMESTAMPTZ,
    client_note TEXT,
    questionnaire JSONB,
    questionnaire_submitted_at TIMESTAMPTZ,
    messages JSONB DEFAULT '[]'::jsonb,
    total_price NUMERIC,
    currency TEXT DEFAULT 'INR',
    payment_provider TEXT DEFAULT 'razorpay',
    accept_international_cards BOOLEAN DEFAULT false,
    client_country TEXT,
    payments JSONB DEFAULT '[]'::jsonb,
    project_days INTEGER,
    custom_questions JSONB DEFAULT '[]'::jsonb,
    interest_chat_history JSONB DEFAULT '[]'::jsonb,
    phase_data JSONB,
    audit JSONB DEFAULT '[]'::jsonb,
    chat_messages JSONB DEFAULT '[]'::jsonb,
    client_id TEXT,
    last_interaction_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_submissions_status ON synapsis.submissions(status);
CREATE INDEX IF NOT EXISTS idx_submissions_date ON synapsis.submissions(date DESC);
CREATE INDEX IF NOT EXISTS idx_deals_token ON synapsis.deals(token);
CREATE INDEX IF NOT EXISTS idx_deals_status ON synapsis.deals(status);
CREATE INDEX IF NOT EXISTS idx_deals_submission_id ON synapsis.deals(submission_id);

-- 4. Updated at trigger for submissions
CREATE OR REPLACE FUNCTION synapsis.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_submissions_updated_at ON synapsis.submissions;
CREATE TRIGGER update_submissions_updated_at
    BEFORE UPDATE ON synapsis.submissions
    FOR EACH ROW
    EXECUTE FUNCTION synapsis.update_updated_at_column();

DROP TRIGGER IF EXISTS update_deals_updated_at ON synapsis.deals;
CREATE TRIGGER update_deals_updated_at
    BEFORE UPDATE ON synapsis.deals
    FOR EACH ROW
    EXECUTE FUNCTION synapsis.update_updated_at_column();
